database = "botcenter.db"
listen = "0.0.0.0:5001"
timeout_ms = 3000

relays = [
  # "wss://relay.keychat.io",
  "wss://backup.keychat.io",
]

[cashu]
allow_free = false
allow_pending = false
database = "cashu.db"
mints = ["https://8333.space:3338"]
